CREATE TABLE IF NOT EXISTS "Books"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" varchar(200) NOT NULL,
    "Author" varchar(200),
    "Price" numeric(10,2),
    "Quantity" integer,
    "Category" varchar(100)
);

INSERT INTO "Books" ("Title","Author","Price","Quantity","Category")
VALUES
('Lap trinh C#','Nguyen Van A',120000,5,'CNTT'),
('Co so du lieu','Tran Van B',150000,3,'CNTT'),
('ASP.NET MVC','Le Van C',180000,8,'Web');
